--사용자별 닉네임의 게시글 개수


SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

SELECT NICKNAME, COUNT(*) 
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NICKNAME;

SELECT NICKNAME, TITLE 
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID;


--각 게시글의 제목, 댓글 개수 출력
--게시글에 댓글이 없는 경우 0으로 출력
SELECT B.boardno, B.TITLE, COUNT(C.COMMENTNO)
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.boardno, B.TITLE
ORDER BY b.boardno;

SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;


SELECT B.TITLE, COUNT(C.COMMENTNO)
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.TITLE
ORDER BY COUNT(C.COMMENTNO) DESC;


-- 게시글 번호, 게시글 제목, 내용, 작성일, 작성자 닉네임, 댓글 개수(없으면0) 출력


SELECT B.BOARDNO, B.TITLE, B.CONTENTS, B.CDATETIME, U.NICKNAME, COUNT(C.COMMENTNO)
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
LEFT JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.BOARDNO, B.TITLE, B.CONTENTS , B.CDATETIME , U.USERID, U.NICKNAME
ORDER BY B.BOARDNO DESC;


SELECT B.BOARDNO, TITLE, B.CONTENTS, B.CDATETIME, NICKNAME , COMMENT_CNT
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
INNER JOIN(
SELECT B.boardno, COUNT(C.COMMENTNO) AS COMMENT_CNT
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.boardno) T ON B.BOARDNO = T.BOARDNO;


-- CASE - WHEN
-- STU, PROFESSOR
-- 1. PROFESSOR 테이블에서 400이상의 급여를 받으면 A,
-- 300~400 사이면  B, 나머지는 C로 출력
-- 교수이름, 급여 등급(a~c)
SELECT * FROM PROFESSOR;
-- CASE ~ WHEN (DECODE보다 좀더 복잡한 처리 가능한 IF문)
SELECT
      NAME,
    PAY, 
    CASE
        WHEN PAY >= 400 THEN 'A'
        WHEN PAY BETWEEN 300 AND 500 THEN 'B'
        ELSE 'C'
    END 급여등급
FROM PROFESSOR P;
--LEFT JOIN ;