-- 조인

SELECT * FROM STUDENT;

SELECT * FROM ENROL;

SELECT * FROM SUBJECT;


SELECT *
FROM STUDENT S;

-- 오라클 조인, ANSI 조인
-- 조인 -> 2개이상의 테이블을 연결해서 데이터를 도출하는 방법
-- 관계형 데이터베이스의 핵심 문법
SELECT * FROM STUDENT; -- 
SELECT * FROM ENROL; 
-- FK => ENROL테이블의 SUB_NO가 STUDENT테이블 PK값인 STU_NO를 참조

SELECT * FROM SUBJECT;
-- FK => ENROL테이블의 SUB_NO가 STUDENT테이블 PK값인 STU_NO를 참조

SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT S.*, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- 학번, 이름, 학과, 평균점수 출력
SELECT S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT;


SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;
--교수번호, 교수이름, 학과명 출력
SELECT PROFNO, NAME, D.DNAME 
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO;


--쪼인? 조인? 쬬인?
SELECT * FROM EMP;
SELECT * FROM DEPT;
-- 사번, 이름, 직급(JOB), 부서명(DNAME) 출력
SELECT EMPNO, ENAME, JOB, DNAME 
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;



SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
--------------------
-- 학번, 이름, 학과, 시험점수 출력 STUDENT ENROL
-- + 과목명 SUBJECT
SELECT 
S.STU_NO 학번, STU_NAME 이름, STU_DEPT 학과, E.ENR_GRADE 시험점수, SUB.SUB_NAME 과목명
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;

SELECT S.STU_NO 학번, STU_NAME 이름, STU_DEPT 학과, ENR_GRADE 시험점수, SUB.SUB_NAME 과목명
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;


----
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

--SELF JOIN (자가? 조인)

SELECT E1.ENAME, E2.ENAME 매니저이름 
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;
--WHERE E1.ENAME = 'ALLEN';


SELECT * FROM department;
-- 공과대학에 속하는 모든학과 출력
SELECT D1.DNAME 
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
WHERE D2.PART = 10;


-- 공과대학에 속하는 모든학과 출력
SELECT D3.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART
WHERE D1.DNAME = '공과대학';

SELECT * FROM DEPARTMENT;
-- 공과대학에 속한 학과들 출력

SELECT D3.DNAME1
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART
WHERE D1.DNAME = '공과대학';






