DELETE FROM PROFESSOR WHERE LENGTH(ID) < 6 ;

SELECT * FROM STUDENT;

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES ('12341234','홍길동','기계');

ROLLBACK;

INSERT INTO STUDENT
VALUES ('12341234','김철수','전기전자',1,'A','M',175, NULL);