1.각 직급별 가장 많음 급여와 받는 교수의 이름 급여 출력
PROFESSOR
SELECT * FROM PROFESSOR;

SELECT MAX(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT NAME, P.PAY, P.POSITION 
FROM PROFESSOR P
INNER JOIN (SELECT POSITION, MAX(PAY) MAXPAY FROM PROFESSOR GROUP BY POSITION) TP 
            ON P.PAY = TP.MAXPAY AND P.POSITION = TP.POSITION;


--선생님 버전
SELECT * 
FROM PROFESSOR P
INNER JOIN (SELECT POSITION ,MAX(PAY) MAX_PAY
            FROM PROFESSOR
            GROUP BY POSITION) T ON P.POSITION = T.POSITION AND P.PAY = T.MAX_PAY;




2. 본인 부서의 평균 급여보다 높은 급여를 받는 사원의 사번 이름 급여출력
EMP
SELECT * FROM EMP;


(SELECT E.DEPTNO, AVG(E.SAL) 
FROM EMP E 
GROUP BY E.DEPTNO);

SELECT E.EMPNO, E.ENAME, E.SAL , E.DEPTNO, AVG(E.SAL)
FROM EMP E
INNER JOIN (SELECT E.DEPTNO DEPTNO, AVG(E.SAL) AS AVGSAL 
            FROM EMP E 
            GROUP BY E.DEPTNO) T
            ON E.SAL > T.AVGSAL AND E.DEPTNO = T.DEPTNO
GROUP BY E.EMPNO, E.ENAME, E.SAL , E.DEPTNO ;


SELECT DEPTNO, ANG(SAL)
FROM EMP
GROUP BY DEPTNO;


--선생님 버전
SELECT EMPNO, ENAME, SAL, ROUND(AVG_SAL) 
FROM EMP E
INNER JOIN (SELECT DEPTNO, AVG(SAL) AVG_SAL 
            FROM EMP
            GROUP BY DEPTNO
            ) T ON E.DEPTNO = T.DEPTNO AND E.SAL > T.AVG_SAL;
