--1. '컴퓨터정보' 학과에 속한 학생들의 학번, 이름, 평균시험점수를 출력하시오
--(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT S.STU_NO,S.STU_NAME, AVG(E.ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE S.STU_DEPT = '컴퓨터정보'
GROUP BY S.STU_NO,S.STU_NAME;

SELECT S.STU_NO, S.STU_NAME, AVG(E.ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, S.STU_NAME;


--2. '강종영' 교수의 과목 시험을 본 학생의 학번, 이름, 점수, 과목명을 출력하시오.
--(STUDENT, ENROL, SUBJECT)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.STU_NO, S.STU_NAME , E.ENR_GRADE, SUB.SUB_NAME -- ,E.SUB_NO, SUB.SUB_PROF
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB.SUB_PROF='강종영';

SELECT S.STU_NO, STU_NAME, ENR_GRADE, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_PROF = '강종영';



--3. 학생들의 이름, 시험을 본 개수를 출력하시오. 
--- 시험을 안본 사람은 출력을 안하거나 0으로 출력하거나 상관없음.
--(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL; -- 이게 시험본 점수가 있는 테이블

SELECT S.STU_NAME , COUNT(S.STU_NAME)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NAME;

SELECT STU_NAME, COUNT(*)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;





--4. 모든 학생들의 시험 평균 점수보다 높은 평균점수를 가지는 학생들의 학번, 이름, 평균점수를 출력하시오.
--(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL; -- 이게 시험본 점수가 있는 테이블

--SELECT S.STU_NO, S.STU_NAME , AVG(EE.ENR_GRADE)
--FROM STUDENT S
--INNER JOIN ENROL EE ON S.STU_NO = EE.STU_NO
--WHERE 1=1
--AND S.STU_NO IN(
--        SELECT EEE.STU_NO 
--        FROM ENROL EEE
--        WHERE EEE.ENR_GRADE >(SELECT AVG(E.ENR_GRADE)
--                          FROM STUDENT SS
--                          INNER JOIN ENROL E ON SS.STU_NO = E.STU_NO)
--    ) 
--AND EE.ENR_GRADE > (SELECT AVG(E.ENR_GRADE)
--                          FROM STUDENT SS
--                          INNER JOIN ENROL E ON SS.STU_NO = E.STU_NO)
--GROUP BY (S.STU_NO, S.STU_NAME);



SELECT AVG(E.ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT S.STU_NO, STU_NAME, AVG(E.ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME
HAVING AVG(ENR_GRADE)>
                    (SELECT AVG(E.ENR_GRADE)
                    FROM STUDENT S
                    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO);


--5. 사원번호, 이름, 급여 등급, 사수(MANAGER)이름을 출력하시오.
--(EMP, SALGRADE)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT E.EMPNO, E.ENAME, S.GRADE, E.MGR
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT E.EMPNO, E.ENAME, GRADE, E2.ENAME
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO;


--6. 부서별 급여의 평균 등급을 출력하시오. - 부서명, 급여 평균 등급 출력
--(EMP, SALGRADE, DEPT)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

SELECT D.DNAME,S.GRADE--, AVG(E.SAL)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY  D.DNAME , S.GRADE;


SELECT D.DNAME, ROUND(AVG(E.SAL),2)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY  D.DEPTNO,D.DNAME ;


--7. 인문대학에 속한 교수의 이름을 모두 출력하시오.
--(PROFESSOR, DEPARTMENT)
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

--SELECT P.NAME , D.DNAME
--FROM PROFESSOR P 
--INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
--INNER JOIN DEPARTMENT D2 ON D2.DEPTNO = D.PART
--INNER JOIN DEPARTMENT D3 ON D3.DEPTNO = D2.PART
--WHERE D3.DNAME = '인문대학';


SELECT NAME, D3.DNAME
FROM PROFESSOR P 
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '인문대학';






---------------------------------------------
--5. 각 부서별로 급여가 가장 높은 직원의 이름을 구해 보시오.
-- * 서브쿼리 배운 후 수정, + 조인
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT E.DEPTNO, ENAME, MAX_SAL 
FROM EMP E
INNER JOIN (
    SELECT DEPTNO, MAX(SAL) MAX_SAL
    FROM EMP
    GROUP BY DEPTNO
) E2 ON E.DEPTNO = E2.DEPTNO AND E.SAL = E2.MAX_SAL;

