
SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),1)
FROM STUDENT
GROUP BY  STU_DEPT;

SELECT * FROM PROFESSOR
WHERE LENGTH(ID) >= 6;

UPDATE PROFESSOR
SET
    PAY = PAY + 50
WHERE LENGTH(ID) >= 6;    

ROLLBACK;

DELETE FROM PROFESSOR;

ROLLBACK;